name: jbook_BCA
channels:
  - conda-forge
  - defaults
dependencies:
  - arviz
  - cartopy
  - geopandas
  - jax
  - jaxlib
  - matplotlib
  - numpy
  - numpyro
  - pandas
  - python=3.12
  - scikit-learn=1.6.1
  - scipy
  - seaborn
  - tinygp
  - tqdm
  - xarray
  - ipykernel
  - fiona
  - netcdf4
  - h5netcdf
